name: mansu-blockchain-core
project: mansu-project
namespace: sandbox
values: |-
  fullnameOverride: mansu-blockchain-core
  image: 
    repository: afrioneltd/mansu-crypto-blockchain:app-12
  namespace: sandbox
  containerPort: 3000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: blockchain-core
    domain: mansu.io
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "200Mi"
      cpu: "300m"
  lProbe:
    enabled: true
    path: /health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  rProbe:
    enabled: true
    path: /health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  env:
    enabled: true
    envFrom:
      - configMapRef:
          name: blockchain-core
      - secretRef:
          name: blockchain-core-test

{{- if .Values.env.enabled }}
{{- range .Values.env.envFrom }}
{{- if hasKey . "secretRef" }}
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ $.Values.fullnameOverride }}
spec:
  externalSecretName: {{ .secretRef.name }}
  refreshTime: "1m"
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ $.Values.namespace }}
  externalSecretSpec:
    secretStoreRef:
      name: awssecretsmanager
      kind: ClusterSecretStore
    refreshInterval: 1m
    target:
      name: {{ .secretRef.name }}
      creationPolicy: Owner
    dataFrom:
      - extract:
          key: {{ .secretRef.name }}
{{- end }}
{{- end }}
{{- end }}